version: "3"

services:
  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: globis
      POSTGRES_DB: sql_dojo

volumes:
  db-store:
